# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qwerty.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1156, 1023)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_11 = QtWidgets.QWidget(self.centralwidget)
        self.widget_11.setObjectName("widget_11")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_11)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget = QtWidgets.QWidget(self.widget_11)
        self.widget.setMinimumSize(QtCore.QSize(800, 600))
        self.widget.setObjectName("widget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.figure = QtWidgets.QGraphicsView(self.widget)
        self.figure.setObjectName("figure")
        self.verticalLayout_7.addWidget(self.figure)
        self.verticalLayout_4.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.widget_11)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 360))
        self.widget_2.setMaximumSize(QtCore.QSize(16777215, 360))
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget_2)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_3.setContentsMargins(9, -1, 9, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_3.setObjectName("groupBox_3")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 20, 931, 311))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_13 = QtWidgets.QWidget(self.layoutWidget)
        self.widget_13.setObjectName("widget_13")
        self.label = QtWidgets.QLabel(self.widget_13)
        self.label.setGeometry(QtCore.QRect(20, 0, 121, 21))
        self.label.setObjectName("label")
        self.component_combo = QtWidgets.QComboBox(self.widget_13)
        self.component_combo.setGeometry(QtCore.QRect(190, 0, 91, 22))
        self.component_combo.setObjectName("component_combo")
        self.verticalLayout_2.addWidget(self.widget_13)
        self.widget_8 = QtWidgets.QWidget(self.layoutWidget)
        self.widget_8.setObjectName("widget_8")
        self.label_2 = QtWidgets.QLabel(self.widget_8)
        self.label_2.setGeometry(QtCore.QRect(20, 0, 111, 21))
        self.label_2.setObjectName("label_2")
        self.time_step_spin = QtWidgets.QSpinBox(self.widget_8)
        self.time_step_spin.setGeometry(QtCore.QRect(190, 0, 91, 22))
        self.time_step_spin.setStyleSheet("")
        self.time_step_spin.setObjectName("time_step_spin")
        self.verticalLayout_2.addWidget(self.widget_8)
        self.widget_3 = QtWidgets.QWidget(self.layoutWidget)
        self.widget_3.setObjectName("widget_3")
        self.label_3 = QtWidgets.QLabel(self.widget_3)
        self.label_3.setGeometry(QtCore.QRect(20, 0, 141, 21))
        self.label_3.setObjectName("label_3")
        self.freq_min_spin = QtWidgets.QSpinBox(self.widget_3)
        self.freq_min_spin.setGeometry(QtCore.QRect(190, 0, 91, 22))
        self.freq_min_spin.setObjectName("freq_min_spin")
        self.freq_max_spin = QtWidgets.QSpinBox(self.widget_3)
        self.freq_max_spin.setGeometry(QtCore.QRect(310, 0, 91, 21))
        self.freq_max_spin.setObjectName("freq_max_spin")
        self.label_10 = QtWidgets.QLabel(self.widget_3)
        self.label_10.setGeometry(QtCore.QRect(290, 0, 51, 21))
        self.label_10.setObjectName("label_10")
        self.verticalLayout_2.addWidget(self.widget_3)
        self.widget_10 = QtWidgets.QWidget(self.layoutWidget)
        self.widget_10.setObjectName("widget_10")
        self.label_4 = QtWidgets.QLabel(self.widget_10)
        self.label_4.setGeometry(QtCore.QRect(20, 0, 121, 21))
        self.label_4.setObjectName("label_4")
        self.color_combo = QtWidgets.QComboBox(self.widget_10)
        self.color_combo.setGeometry(QtCore.QRect(190, 0, 91, 22))
        self.color_combo.setObjectName("color_combo")
        self.verticalLayout_2.addWidget(self.widget_10)
        self.widget_4 = QtWidgets.QWidget(self.layoutWidget)
        self.widget_4.setObjectName("widget_4")
        self.label_5 = QtWidgets.QLabel(self.widget_4)
        self.label_5.setGeometry(QtCore.QRect(20, 0, 101, 21))
        self.label_5.setObjectName("label_5")
        self.xlabel_input = QtWidgets.QLineEdit(self.widget_4)
        self.xlabel_input.setGeometry(QtCore.QRect(110, 0, 421, 20))
        self.xlabel_input.setObjectName("xlabel_input")
        self.verticalLayout_2.addWidget(self.widget_4)
        self.widget_6 = QtWidgets.QWidget(self.layoutWidget)
        self.widget_6.setObjectName("widget_6")
        self.label_9 = QtWidgets.QLabel(self.widget_6)
        self.label_9.setGeometry(QtCore.QRect(20, 0, 131, 31))
        self.label_9.setObjectName("label_9")
        self.ylabel_input = QtWidgets.QLineEdit(self.widget_6)
        self.ylabel_input.setGeometry(QtCore.QRect(110, 0, 421, 20))
        self.ylabel_input.setObjectName("ylabel_input")
        self.verticalLayout_2.addWidget(self.widget_6)
        self.widget_5 = QtWidgets.QWidget(self.layoutWidget)
        self.widget_5.setObjectName("widget_5")
        self.label_6 = QtWidgets.QLabel(self.widget_5)
        self.label_6.setGeometry(QtCore.QRect(20, 10, 47, 13))
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_11 = QtWidgets.QLabel(self.widget_5)
        self.label_11.setGeometry(QtCore.QRect(20, 0, 101, 21))
        self.label_11.setObjectName("label_11")
        self.window_combo = QtWidgets.QComboBox(self.widget_5)
        self.window_combo.setGeometry(QtCore.QRect(130, 0, 91, 22))
        self.window_combo.setObjectName("window_combo")
        self.verticalLayout_2.addWidget(self.widget_5)
        self.widget_9 = QtWidgets.QWidget(self.layoutWidget)
        self.widget_9.setObjectName("widget_9")
        self.label_12 = QtWidgets.QLabel(self.widget_9)
        self.label_12.setGeometry(QtCore.QRect(20, 0, 101, 21))
        self.label_12.setObjectName("label_12")
        self.autocorr_button = QtWidgets.QPushButton(self.widget_9)
        self.autocorr_button.setGeometry(QtCore.QRect(130, 0, 91, 23))
        self.autocorr_button.setStyleSheet("QPushButton:hover {\n"
"    background-color: rgb(100, 100, 100);  \n"
"    border: 1px solid rgb(80, 80, 80);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(50, 50, 50);  \n"
"    border: 1px solid rgb(30, 30, 30);\n"
"}")
        self.autocorr_button.setCheckable(True)
        self.autocorr_button.setObjectName("autocorr_button")
        self.verticalLayout_2.addWidget(self.widget_9)
        self.widget_7 = QtWidgets.QWidget(self.layoutWidget)
        self.widget_7.setObjectName("widget_7")
        self.label_7 = QtWidgets.QLabel(self.widget_7)
        self.label_7.setGeometry(QtCore.QRect(20, 0, 101, 21))
        self.label_7.setObjectName("label_7")
        self.dpi_spin = QtWidgets.QLineEdit(self.widget_7)
        self.dpi_spin.setGeometry(QtCore.QRect(130, 0, 91, 20))
        self.dpi_spin.setObjectName("dpi_spin")
        self.verticalLayout_2.addWidget(self.widget_7)
        self.widget_14 = QtWidgets.QWidget(self.layoutWidget)
        self.widget_14.setObjectName("widget_14")
        self.label_8 = QtWidgets.QLabel(self.widget_14)
        self.label_8.setGeometry(QtCore.QRect(20, 0, 251, 16))
        self.label_8.setObjectName("label_8")
        self.null_points_spin = QtWidgets.QSpinBox(self.widget_14)
        self.null_points_spin.setGeometry(QtCore.QRect(261, 0, 101, 22))
        self.null_points_spin.setObjectName("null_points_spin")
        self.verticalLayout_2.addWidget(self.widget_14)
        self.horizontalLayout_3.addWidget(self.groupBox_3)
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox.setMaximumSize(QtCore.QSize(180, 16777215))
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.file_button = QtWidgets.QPushButton(self.groupBox)
        self.file_button.setStyleSheet("QPushButton:hover {\n"
"    background-color: rgb(100, 100, 100);  \n"
"    border: 1px solid rgb(80, 80, 80);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(50, 50, 50);  \n"
"    border: 1px solid rgb(30, 30, 30);\n"
"}")
        self.file_button.setObjectName("file_button")
        self.verticalLayout.addWidget(self.file_button)
        self.plt_btn = QtWidgets.QPushButton(self.groupBox)
        self.plt_btn.setStyleSheet("QPushButton:hover {\n"
"    background-color: rgb(100, 100, 100);  \n"
"    border: 1px solid rgb(80, 80, 80);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(50, 50, 50);  \n"
"    border: 1px solid rgb(30, 30, 30);\n"
"}")
        self.plt_btn.setObjectName("plt_btn")
        self.verticalLayout.addWidget(self.plt_btn)
        self.save_button = QtWidgets.QPushButton(self.groupBox)
        self.save_button.setStyleSheet("QPushButton:hover {\n"
"    background-color: rgb(100, 100, 100);  \n"
"    border: 1px solid rgb(80, 80, 80);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(50, 50, 50);  \n"
"    border: 1px solid rgb(30, 30, 30);\n"
"}")
        self.save_button.setObjectName("save_button")
        self.verticalLayout.addWidget(self.save_button)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalLayout_3.addWidget(self.groupBox)
        self.horizontalLayout_2.addWidget(self.groupBox_2)
        self.verticalLayout_4.addWidget(self.widget_2)
        self.verticalLayout_3.addWidget(self.widget_11)
        mainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Анализатор спектра"))
        self.groupBox_3.setTitle(_translate("mainWindow", "Параметры"))
        self.label.setText(_translate("mainWindow", "Компоненты:"))
        self.label_2.setText(_translate("mainWindow", "Шаг времени (фс):"))
        self.label_3.setText(_translate("mainWindow", "Диапозон частот: (см⁻¹):"))
        self.label_10.setText(_translate("mainWindow", "до"))
        self.label_4.setText(_translate("mainWindow", "Цвет графика:"))
        self.label_5.setText(_translate("mainWindow", "Подпись оси X:"))
        self.label_9.setText(_translate("mainWindow", "Подпись оси Y:"))
        self.label_11.setText(_translate("mainWindow", "Оконная функция:"))
        self.label_12.setText(_translate("mainWindow", "Автокорреляция:"))
        self.autocorr_button.setText(_translate("mainWindow", "Вкл/Выкл"))
        self.label_7.setText(_translate("mainWindow", "Значение DPI:"))
        self.label_8.setText(_translate("mainWindow", "Сколько точек обнулить в начале спектра:"))
        self.groupBox.setTitle(_translate("mainWindow", "Действия"))
        self.file_button.setText(_translate("mainWindow", "Загрузить файл"))
        self.plt_btn.setText(_translate("mainWindow", "Построить график"))
        self.save_button.setText(_translate("mainWindow", "Сохранить график"))
